# Notebook da aula ainda não disponível, não consegui copiar os códigos, reassistir.

In [1]:
import scipy
from scipy import stats
import numpy as np

In [3]:
matrix = np.array([[8, 0, 3, 4, 6], [5, 6, 1, 8, 9], [8, 0, 0, 5, 10]])
novoUser = [8, 0, 2, 3, 0]
nao_assistidos = [0, 1, 0, 0, 1]
print(matrix)
nomeFilmes = ["Round 6", "A invocação do mal", "9 desconhecidos", "You", "La Casa de Papel"]

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [5]:
#criando um vetor com 3 posições e preencher com zero
similarity = [0] * 3
print(matrix[0][0])
print(matrix[1][0])
print(matrix[1, :])
#para cada usuário no sistema...
for i in range(0, 3):
  #vamos pegar os dados desse usuário
  temp = matrix[i, :]

  print(i, temp)
  #mas queremos apenas comparar os dados que o novo user assistiu (novouser != 0)
  tempUser = [t for n, t in zip(novoUser, temp) if n != 0]
  tempNovoUser = [n for n in novoUser if n !=0]

  #para verificar o processo
  print("user:", i)
  print(tempUser, tempNovoUser)

  #vamos usar a biblioteca scipy.stats que já calcula o pearson
  similarity[i] = scipy.stats.pearsonr(tempUser, tempNovoUser)[0] #a função retorna
print()

print(similarity)
#pra cada usuário novo q tá sendo inserido na base, a gente calcula a probabilidade de ele ter interesse naquele conteúdo que a gente tá analisando
#baseado na info que temos daquele usuário, podemos relacionar o quanto q usuários com mesmo perfil podem ter interesse naquele conteúdo

8
5
[5 6 1 8 9]
0 [8 0 3 4 6]
user: 0
[8, 3, 4] [8, 2, 3]
1 [5 6 1 8 9]
user: 1
[5, 1, 8] [8, 2, 3]
2 [ 8  0  0  5 10]
user: 2
[8, 0, 5] [8, 2, 3]

[0.9994237971287663, 0.23621543814299698, 0.8723686098443353]


olhando a última linha do resultado, a gente sabe q esse usuário tem maior interesse pelo primeiro conteudo (99%), pelo terceiro (87%) e pouco interesse pelo segundo (23%)

In [10]:
nota_peso = np.zeros((3, 5))

for nUser in range(3):
  for nFilme in range(5):
    print('nota_peso[', nUser,'][', nFilme,'] = nao_assistidos[', nFilme, '] * matrix[', nUser,'][', nFilme,'] * similarity[', nUser,']')
    print('nota_peso[', nUser,'][', nFilme,'] = ', nao_assistidos[nFilme],' * ' ,matrix[', nUser,'][', nFilme,'],' * ' ,similarity[', nUser,']')
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

print(nota_peso)

SyntaxError: ignored